replicaCount: 1

persistence:
  enabled: false
  storage: 1Gi

ingress:
  enabled: true

cronjobs:
  enabled: false

worker:
  enabled: false
  replicaCount: 1
  cmd: "php /app/artisan queue:work --sleep=3 --tries=3"

postgres:
  enabled: true
  persistence:
    enabled: false
    size: 1Gi
    
mysql:
  enabled: false
  imageTag: "5.7.14"
  persistence:
    enabled: true
    size: 1Gi

redis:
  enabled: false

elasticsearch:
  enabled: true
  persistence:
    enabled: false
    size: 1Gi
