stages:
  - tests
  - build
  - deploy
  - migrations

variables:
  POD: "kubernetes/test.yaml"
  RC: "kubernetes/dev/rc.yaml"
  CI_USER: "application"
  CI_SHELL: "/bin/bash"


build_development:
  stage: build
  script:
    - build kubernetes/dev/php/Dockerfile
    - build dep kubernetes/dev/sphinx/Dockerfile
    - build dep kubernetes/dev/postgres/Dockerfile
  only:
    - master
  tags:
    - k8s-dev

deploy_development:
  stage: deploy
  script:
    - deploy
    - replace
    - proxy_updater dev.wip.ronasit.com
  environment:
    name: "wip-dev"
  only:
    - master
  tags:
    - k8s-dev

migrations_development:
  stage: migrations
  script:
    - run php artisan migrate --force
  only:
    - master
  tags:
    - k8s-dev

tests:
  stage: tests
  variables:
    POSTGRES_USER: pguser
    POSTGRES_PASSWORD: ""
    POSTGRES_DB: pgdb
  image: webdevops/php:ubuntu-16.04
  services:
    - postgres:9.6
  before_script:
    - apt-get -qq update && apt-get -qq install php-pgsql php-imagick > /dev/null
    - cp .env.dev.testing .env
    - composer -q install
  script:
    - php vendor/bin/phpunit --stop-on-failure
  after_script:
    - cat storage/logs/laravel.log || true
  only:
    - master
  tags:
    - docker
    - linux
