replicaCount: 1

persistence:
  enabled: false
  storage: 1Gi

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging  #letsencrypt-prod for production

cronjobs:
  enabled: true

worker:
  enabled: true
  replicaCount: 1
  cmd: "php /app/artisan queue:work --sleep=3 --tries=3"

postgres:
  enabled: true
  persistence:
    enabled: false
    size: 1Gi
    
mysql:
  enabled: false
  imageTag: "5.7.14"
  persistence:
    enabled: true
    size: 1Gi

redis:
  enabled: false

elasticsearch:
  enabled: false
  persistence:
    enabled: false
    size: 1Gi
