replicaCount: 1

persistence:
  enabled: false
  existingClaim: ""
  storage: 1Gi

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging  #letsencrypt-prod for production

cronjobs:
  enabled: false

worker:
  enabled: false
  replicaCount: 1
  cmd: "php /app/artisan queue:work --sleep=3 --tries=3"

migrate:
  enabled: true
  timeout: 260
  cmd: "php artisan migrate --force"

# For Google Cloud Storage
gcs:
  enabled: false
  projectId: "ronas-it-development"
  bucketName: "ronasit-development"
  apiUri: "https://storage.googleapis.com/ronasit-development"
  key: "secret"

# For Google Cloud SQL
sqlproxy:
  enabled: false
  serviceAccountKey: ""
  instance: ""
  project: ""
  region: ""
  port: "5432"
  sqlUser: ""
  sqlPassword: ""
  sqlDatabase: ""

postgres:
  enabled: true
  persistence:
    enabled: false
    size: 1Gi
    
mysql:
  enabled: false
  image: "ronasit/mysql"
  imageTag: "5.7-lowmem"
  persistence:
    enabled: true
    size: 1Gi

redis:
  enabled: false

elasticsearch:
  enabled: false
  persistence:
    enabled: false
    size: 1Gi
