apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: project-dev
    spec:
      containers:
      - image: gcr.io/ronas-it-development/project-laravel-api/development
        imagePullPolicy: Always
        name: project-dev
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "/postrun.sh"
        resources:
          requests:
            cpu: 0m
        volumeMounts:
          - name: storage
            mountPath: /storage
        env:
          - name: WEB_DOCUMENT_ROOT
            value: "/app/public"
          - name: WEB_DOCUMENT_INDEX
            value: "index.php"
      - image: mysql:5.6
        resources:
          requests:
            cpu: 0m
        imagePullPolicy: Always
        name: project-dev-mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "bC&(HBIAcda"
          - name: MYSQL_PASSWORD
            value: "bC&(HBIAcda"
          - name: MYSQL_USER
            value: "project"
          - name: MYSQL_DATABASE
            value: "project"
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db
      - image: redis
        resources:
          requests:
            cpu: 0m
        imagePullPolicy: Always
        name: redis
        volumeMounts:
          - mountPath: /data
            name: redis
      volumes:
        - name: db
          hostPath:
            path: /mnt/disks/storage/project-dev/mysql
        - name: storage
          hostPath:
            path: /mnt/disks/storage/project-dev/storage
        - name: redis
          hostPath:
            path: /mnt/disks/storage/project-dev/redis
