apiVersion: v1
kind: ReplicationController
metadata:
  name: wip-dev
spec:
  replicas: 1
  selector:
    app: wip-dev
  template:
    metadata:
      name: wip-dev
      labels:
        app: wip-dev
    spec:
      containers:
      - image: gcr.io/ronas-it-development/wip-erp/development
        name: wip-php
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
                - "sh"
                - "/postrun.sh"
        resources:
          requests:
            cpu: 0m
        env:
          - name: WEB_DOCUMENT_ROOT
            value: "/app/public"
          - name: WEB_DOCUMENT_INDEX
            value: "index.php"
        volumeMounts:
          - name: storage
            mountPath: /storage
          - name: documentation
            mountPath: /app/storage/documentation
      - image: postgres:9.5
        imagePullPolicy: Always
        name: wip-postgres
        env:
          - name: POSTGRES_PASSWORD
            value: "bC&(HBIAcda"
          - name: POSTGRES_USER
            value: "wip"
          - name: POSTGRES_DB
            value: "wip"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db
      volumes:
        - name: db
          hostPath:
            path: /mnt/storage/wip-dev/db
        - name: storage
          hostPath:
            path: /mnt/storage/wip-dev/storage
        - name: documentation
          hostPath:
            path: /mnt/storage/wip-dev/documentation
